# Generated by Django 4.1.7 on 2023-03-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethod', '0002_remove_paymenthistory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='last_four_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
