# Generated by Django 4.1.7 on 2023-03-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethod', '0007_paymentmethod_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurring',
            name='duration',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
    ]
