# Generated by Django 4.1.7 on 2023-03-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethod', '0008_remove_recurring_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurring',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='recurring',
            name='email',
        ),
        migrations.RemoveField(
            model_name='recurring',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='recurring',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='recurring',
            name='plan_id',
        ),
        migrations.RemoveField(
            model_name='recurring',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='recurring',
            name='status',
        ),
        migrations.RemoveField(
            model_name='recurring',
            name='subscription_id',
        ),
    ]
