# Generated by Django 4.1.7 on 2023-03-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpay', '0003_product_remove_payment_is_recurring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
