# Generated by Django 4.1.7 on 2023-03-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpay', '0004_remove_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
