# Generated by Django 4.1.7 on 2023-03-30 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpay', '0006_payment_is_recurring_payment_next_payment_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='next_payment_due',
        ),
    ]
