# Generated by Django 4.1.7 on 2023-03-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testpay', '0007_remove_payment_next_payment_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='is_recurring',
            field=models.BooleanField(default=True),
        ),
    ]
