# Generated by Django 4.1.7 on 2023-03-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpay', '0008_alter_payment_is_recurring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
