# Generated by Django 4.1.7 on 2023-03-03 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paymentmethod', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_number',
        ),
        migrations.CreateModel(
            name='Recurring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('yearly', 'Yearly')], max_length=10)),
                ('duration', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled')], max_length=20)),
                ('subscription_id', models.CharField(max_length=50)),
                ('plan_id', models.CharField(max_length=50)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paymentmethod.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
