# Generated by Django 4.1.7 on 2023-03-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethod', '0003_paymentmethod_last_four_digits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_holder_name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='expiration_month',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='expiration_year',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='last_four_digits',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='interval',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='plan_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.DeleteModel(
            name='Recurring',
        ),
    ]
