# Generated by Django 4.1.7 on 2023-03-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethod', '0004_remove_paymentmethod_card_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='cvv',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiration_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiration_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='last_four_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
